/** Özgün Türkçe ve Dil Bilgisi soru paketi. */
export const SEED_QUESTIONS_TURKISH = [
  { topic: 'Türkçe ve Dil Bilgisi', text: 'Aşağıdaki cümlelerin hangisinde “de” bağlacı ayrı yazılmalıdır?', choices: ['Sende bizimle gel.', 'Benimde bu konuda fikrim var.', 'O da toplantıya katılacak.', 'Evdeki dosyaları inceledim.'], answer: 2, reference: 'Yazım kuralları · de bağlacı', explanation: 'Bağlaç olan “de/da” ayrı yazılır. “O da” ifadesindeki de bağlaçtır.' },
  { topic: 'Türkçe ve Dil Bilgisi', text: 'Aşağıdaki cümlelerin hangisinde yazım yanlışı vardır?', choices: ['Her şey zamanla düzelecek.', 'Bugünkü toplantı ertelendi.', 'Hiç bir belge eksik değil.', 'Birçok çalışan salondaydı.'], answer: 2, reference: 'Yazım kuralları · birleşik kelimeler', explanation: '“Hiçbir” kelimesi bitişik yazılır.' },
  { topic: 'Türkçe ve Dil Bilgisi', text: 'Aşağıdaki cümlelerin hangisinde “ki” ayrı yazılmalıdır?', choices: ['Dünkü rapor yeniden düzenlendi.', 'Toplantıdaki herkes söz aldı.', 'Biliyorumki bu işi başaracaksın.', 'Yarınki sınava hazırlandı.'], answer: 2, reference: 'Yazım kuralları · ki bağlacı', explanation: 'Bağlaç olan “ki” ayrı yazılır: “Biliyorum ki...”' },
  { topic: 'Türkçe ve Dil Bilgisi', text: 'Aşağıdaki cümlelerin hangisinde virgül doğru kullanılmıştır?', choices: ['Toplantıya, katılacak mısın?', 'Çalışanlar, raporlarını teslim etti.', 'Dosyaları kontrol ettik, eksikleri not aldık.', 'Yönetici toplantının, ertelendiğini bildirdi.'], answer: 2, reference: 'Noktalama işaretleri · virgül', explanation: 'Birbiri ardınca sıralanan cümleleri ayırmak için virgül kullanılabilir. Doğru kullanım üçüncü seçenektedir.' },
  { topic: 'Türkçe ve Dil Bilgisi', text: '“Dosyaları dikkatle inceledi.” cümlesindeki “dikkatle” sözcüğünün türü nedir?', choices: ['İsim', 'Sıfat', 'Zarf', 'Zamir'], answer: 2, reference: 'Sözcük türleri · zarflar', explanation: '“Dikkatle” fiilin nasıl yapıldığını bildirir; bu nedenle durum zarfıdır.' },
  { topic: 'Türkçe ve Dil Bilgisi', text: 'Aşağıdaki sözcüklerden hangisi yapım eki almıştır?', choices: ['Evler', 'Kitabım', 'Yolculuk', 'Kalemde'], answer: 2, reference: 'Sözcükte yapı · yapım ekleri', explanation: '“Yolculuk” sözcüğündeki “-culuk” yapım ekidir; yeni anlamlı bir sözcük oluşturur.' },
  { topic: 'Türkçe ve Dil Bilgisi', text: '“Çalışanlar, yöneticinin açıklamasını dikkatle dinledi.” cümlesinin öznesi hangisidir?', choices: ['Çalışanlar', 'Yöneticinin', 'Açıklamasını', 'Dikkatle'], answer: 0, reference: 'Cümlenin ögeleri · özne', explanation: 'Eylemi gerçekleştiren “çalışanlar” sözcüğüdür; cümlenin öznesidir.' },
  { topic: 'Türkçe ve Dil Bilgisi', text: 'Aşağıdaki cümlelerin hangisinde neden-sonuç ilişkisi vardır?', choices: ['Hava soğuduğu için pencereleri kapattık.', 'Pencereleri kapatıp dışarı çıktık.', 'Pencereleri kapatacakmış.', 'Pencereleri kapatmayı unutmuş.'], answer: 0, reference: 'Anlam ilişkileri · neden-sonuç', explanation: '“Hava soğuduğu için” bölümü neden, “pencereleri kapattık” bölümü sonuç bildirir.' },
  { topic: 'Türkçe ve Dil Bilgisi', text: '“Bütün çalışanlar eğitim programına katıldı.” cümlesinde “bütün” sözcüğünün türü nedir?', choices: ['İşaret sıfatı', 'Soru sıfatı', 'Belgisiz sıfat', 'Sayı sıfatı'], answer: 2, reference: 'Sıfatlar · belgisiz sıfat', explanation: '“Bütün” sözcüğü ismi belirsiz miktar yönünden belirttiği için belgisiz sıfattır.' },
  { topic: 'Türkçe ve Dil Bilgisi', text: 'Aşağıdaki kelimelerden hangisinin yazımı doğrudur?', choices: ['Yanlız', 'Herkez', 'Malesef', 'Mühendis'], answer: 3, reference: 'Yazım kuralları', explanation: 'Doğru yazım “mühendis”tir. Diğerleri sırasıyla yalnız, herkes ve maalesef olmalıdır.' },
  { topic: 'Türkçe ve Dil Bilgisi', text: '“Yarın Ankara’ya gideceğiz.” cümlesinde kesme işaretinin kullanılma nedeni nedir?', choices: ['Özel ada gelen çekim ekini ayırmak', 'Birleşik kelime oluşturmak', 'Alıntı yapmak', 'Sayıları ayırmak'], answer: 0, reference: 'Noktalama işaretleri · kesme işareti', explanation: 'Özel adlara getirilen çekim ekleri kesme işaretiyle ayrılır: Ankara’ya.' },
  { topic: 'Türkçe ve Dil Bilgisi', text: 'Aşağıdaki cümlelerin hangisinde anlatım bozukluğu vardır?', choices: ['Bu konuda herkes kendi fikrini söyledi.', 'Sorunu birlikte çözmeyi planlıyoruz.', 'Toplantıya yaklaşık yirmiye yakın kişi katıldı.', 'Raporu zamanında teslim etti.'], answer: 2, reference: 'Anlatım bozuklukları · gereksiz sözcük', explanation: '“Yaklaşık” ve “-e yakın” aynı anlamı verdiğinden birlikte kullanılması gereksiz sözcük kullanımına yol açar.' },
  { topic: 'Türkçe ve Dil Bilgisi', text: '“Onu görünce çok sevindim.” cümlesinde altı çizili olduğu varsayılan “onu” sözcüğü hangi türdedir?', choices: ['İsim', 'Zamir', 'Edat', 'Bağlaç'], answer: 1, reference: 'Sözcük türleri · zamirler', explanation: '“Onu” bir ismin yerini tuttuğu için zamirdir.' },
  { topic: 'Türkçe ve Dil Bilgisi', text: 'Aşağıdaki cümlelerin hangisinde soru anlamı soru sözcüğüyle sağlanmıştır?', choices: ['Toplantıya katılacak mısın?', 'Bu raporu kim hazırladı?', 'Rapor hazır mı?', 'Sınavı kazandı mı?'], answer: 1, reference: 'Soru cümleleri', explanation: '“Kim” soru zamiriyle soru anlamı sağlanmıştır; diğer seçeneklerde soru eki kullanılmıştır.' },
  { topic: 'Türkçe ve Dil Bilgisi', text: '“Kurumun yeni hedefleri açıklandı.” cümlesindeki “yeni” sözcüğü hangi görevde kullanılmıştır?', choices: ['İsim', 'Niteleme sıfatı', 'Zarf', 'Edat'], answer: 1, reference: 'Sözcük türleri · sıfatlar', explanation: '“Yeni”, “hedefleri” ismini nitelediği için niteleme sıfatıdır.' }
];
