/** Süleyman'ın sağladığı 399 KHK örnek sınavındaki madde-köklü format esas alınarak hazırlanmış ek soru paketi. */
export const SEED_QUESTIONS_399_EXAM_STYLE = [
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: '399 sayılı KHK’nin 1 inci maddesine göre KHK’nin amacı aşağıdakilerden hangisidir?', choices: ['Yalnızca KİT’lerin kuruluş usullerini düzenlemek', '233 sayılı KHK’ye tabi teşebbüs ve bağlı ortaklıkların personeline ilişkin usul ve esasları düzenlemek', 'KİT’lerin sermaye yapısını belirlemek', 'Yalnızca işçi ücretlerini düzenlemek', 'Özelleştirme usullerini belirlemek'], answer: 1, reference: '399 sayılı KHK · Madde 1', explanation: 'Madde 1, 233 sayılı KHK kapsamındaki teşebbüs ve bağlı ortaklık personelinin özlük düzenini kapsar.' },
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: 'Madde 2’de sayılan temel ilkeler arasında aşağıdakilerden hangisi yer almaz?', choices: ['İşin gerektirdiği nitelikleri taşıyan elemanların işe alınması', 'Verimlilik ve kârlılık ilkelerine bağlı çalıştırma', 'Göreve devamı özendirecek özlük hakları sistemi', 'Yaratıcılık ve girişimciliğin teşviki', 'Personelin siyasi parti üyeliğinin teşviki'], answer: 4, reference: '399 sayılı KHK · Madde 2', explanation: 'Siyasi parti üyeliğinin teşviki temel ilkeler arasında sayılmaz.' },
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: '399 sayılı KHK’ye göre sözleşmeli statüde istihdam edilecek personele ait pozisyonların unvan ve sayıları hangi işlemle tespit edilir?', choices: ['Yönetim kurulu kararı', 'İlgili bakanlığın genelgesi', 'Cumhurbaşkanı Kararı', 'Sayıştay kararı', 'Teşebbüs genel müdürü onayı'], answer: 2, reference: '399 sayılı KHK · Madde 4', explanation: 'Madde 4 uyarınca pozisyonların unvan ve sayıları Cumhurbaşkanı Kararı ile tespit edilir.' },
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: 'Madde 8’e göre aşağıdakilerden hangisi sınava tabi tutulmadan işe alınabilecek kişiler arasında yer alır?', choices: ['İlk defa açıktan işe alınacaklar', 'Memur statüsünden sözleşmeli statüye geçenler', 'Yarışma sınavını kazanamayanlar', 'Yeterlik sınavına girmeyi reddedenler', 'Yeni mezun adaylar'], answer: 1, reference: '399 sayılı KHK · Madde 8', explanation: 'Memur statüsünden sözleşmeli statüye geçenler, maddede yer alan istisna kapsamındadır.' },
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: 'Madde 15’e göre başka iş ve hizmet yasağının kapsamı dışında olan faaliyet aşağıdakilerden hangisidir?', choices: ['Faaliyet konusuna giren mal veya hizmet ticareti yapan şirketlere ortak olmak', 'Esas göreve halel gelmemek kaydıyla eğitim ve öğretim faaliyetinde görev almak', 'Teşebbüsün faaliyet alanında ticari işle bizzat uğraşmak', 'Rakip özel şirkette yönetici olarak çalışmak', 'İzinsiz ikinci görev üstlenmek'], answer: 1, reference: '399 sayılı KHK · Madde 15', explanation: 'Esas göreve halel gelmemek kaydıyla eğitim ve öğretim faaliyeti maddede istisna olarak düzenlenmiştir.' },
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: 'Madde 27’ye göre sicil ve başarı değerlendirmesi sonucunda (A) düzeyinde olanlara temel ücretlerinin yüzde kaçı oranında başarı ücreti ödenir?', choices: ['%2', '%4', '%6', '%8', '%10'], answer: 3, reference: '399 sayılı KHK · Madde 27', explanation: 'A düzeyi için temel ücretin yüzde sekizi oranında başarı ücreti öngörülmüştür.' },
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: 'Madde 28’e göre sosyal güvenlik kuruluşuna prim ödemek suretiyle geçen hizmet süresi 21 yıl ve daha fazla olanlara temel ücretin yüzde kaçı oranında kıdem ücreti verilir?', choices: ['%2', '%3', '%4', '%5', '%6'], answer: 3, reference: '399 sayılı KHK · Madde 28', explanation: '21 yıl ve daha fazla hizmet süresi için kıdem ücreti oranı yüzde beştir.' },
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: 'Madde 45’e göre aşağıdakilerden hangisi sözleşmenin feshini gerektiren hâllerden biri değildir?', choices: ['İzinsiz ve mazeretsiz kesintisiz beş gün göreve gelmemek', 'İşe alınma şartlarından birini sonradan kaybetmek', 'İki sözleşme döneminde art arda (D) düzeyinde olmak', 'Yıllık ücretli izin hakkını kullanmak', 'Görev yeri değişikliğinde süresinde yeni göreve başlamamak'], answer: 3, reference: '399 sayılı KHK · Madde 45', explanation: 'Yıllık izin kullanımı sözleşmenin feshini gerektiren bir hâl değildir.' },
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: 'Madde 46’ya göre sözleşmeli personele savunmasını yapması için verilecek süre en az kaç gündür?', choices: ['3', '5', '7', '10', '15'], answer: 2, reference: '399 sayılı KHK · Madde 46', explanation: 'Savunma için verilecek süre en az yedi gündür.' },
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: 'Madde 50’ye göre disiplin cezasını gerektiren kusurlu hâlin öğrenilmesinden itibaren hangi süre sonunda disiplin kovuşturması yapılamaz?', choices: ['Bir ay', 'Üç ay', 'Altı ay', 'Bir yıl', 'İki yıl'], answer: 2, reference: '399 sayılı KHK · Madde 50', explanation: 'Kusurlu hâlin öğrenilmesinden itibaren altı ay geçtikten sonra disiplin kovuşturması yapılamaz.' },
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: 'Madde 55’e göre görevden uzaklaştırılan sözleşmeli personele bu hâlin devamı süresince sözleşme ücretinin ne kadarı ödenir?', choices: ['Dörtte biri', 'Üçte biri', 'Yarısı', 'Üçte ikisi', 'Tamamı'], answer: 3, reference: '399 sayılı KHK · Madde 55', explanation: 'Görevden uzaklaştırma süresince sözleşme ücretinin üçte ikisi ödenir.' },
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: 'Madde 58’e göre KHK’nin teşebbüs ve bağlı ortaklıklarda uygulanmasında birliği sağlamak ve tereddütleri gidermekle yetkili kurum hangisidir?', choices: ['Sayıştay Başkanlığı', 'Devlet Personel Başkanlığı', 'Hazine ve Maliye Bakanlığı', 'Danıştay', 'Teşebbüs yönetim kurulu'], answer: 1, reference: '399 sayılı KHK · Madde 58', explanation: 'Madde 58’de Devlet Personel Başkanlığı yetkili ve görevli kılınmıştır.' },
];
