/**
 * Original draft questions prepared from the 399 Sayılı KHK article references.
 * Review against the current official consolidated text before public release.
 */
export const SEED_QUESTIONS_399 = [
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: '399 sayılı KHK’nin kapsamındaki teşebbüs ve bağlı ortaklıklarda personel hizmetleri hangi üç statü ile yürütülür?', choices: ['Memurlar, sözleşmeli personel ve işçiler', 'Yalnızca memurlar ve işçiler', 'Yalnızca sözleşmeli personel ve stajyerler', 'Memurlar, akademisyenler ve işçiler'], answer: 0, reference: '399 Sayılı KHK · Madde 3/a', explanation: 'Madde 3/a uyarınca hizmetler memurlar, sözleşmeli personel ve işçiler eliyle gördürülür.' },
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: 'Genel idare esaslarına göre yürütülen asli ve sürekli görevlerde, KHK’de belirtilmeyen hususlarda hangi Kanun uygulanır?', choices: ['4857 Sayılı İş Kanunu', '657 Sayılı Devlet Memurları Kanunu', '5510 Sayılı Kanun', '6331 Sayılı Kanun'], answer: 1, reference: '399 Sayılı KHK · Madde 3/b', explanation: 'Madde 3/b, belirtilenler dışında 657 Sayılı Devlet Memurları Kanunu hükümlerine atıf yapar.' },
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: 'Sözleşmeli personelin haftalık normal çalışma süresi aşağıdakilerden hangisidir?', choices: ['37,5 saat', '40 saat', '42 saat', '45 saat'], answer: 1, reference: '399 Sayılı KHK · Madde 20', explanation: 'Madde 20’ye göre sözleşmeli personelin haftalık çalışma süresi 40 saattir.' },
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: 'Hizmeti on yıla kadar olan sözleşmeli personele yılda kaç gün ücretli izin verilir?', choices: ['14 gün', '18 gün', '20 gün', '26 gün'], answer: 2, reference: '399 Sayılı KHK · Madde 21', explanation: 'Madde 21’de, on yıl dâhil hizmeti on yıla kadar olanlar için 20 gün ücretli izin düzenlenmiştir.' },
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: 'İlk defa açıktan işe alınacak sözleşmeli personel ile yapılan ilk sözleşmenin süresi kaç aydır?', choices: ['3 ay', '6 ay', '12 ay', '24 ay'], answer: 1, reference: '399 Sayılı KHK · Madde 6', explanation: 'Madde 6 uyarınca ilk defa açıktan işe alınacak sözleşmeli personelle altı aylık sözleşme yapılır.' },
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: 'Sözleşmeli olarak işe alınacaklarda aranan asgari yaş koşulu hangisidir?', choices: ['17 yaşını bitirmiş olmak', '18 yaşını tamamlamış olmak', '20 yaşını tamamlamış olmak', '21 yaşını bitirmiş olmak'], answer: 1, reference: '399 Sayılı KHK · Madde 7/b', explanation: 'Madde 7/b’de 18 yaşını tamamlamış olmak şartı yer alır.' },
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: 'Aşağıdakilerden hangisi sözleşmeli personel için açıkça yasaklanan davranışlardan biridir?', choices: ['Eğitim ve öğretim faaliyetinde görev almak', 'Grev kararına katılmak', 'Bilirkişilik yapmak', 'Sosyal güvenlik kuruluşlarının istişari organlarında görev almak'], answer: 1, reference: '399 Sayılı KHK · Madde 14', explanation: 'Madde 14; grev kararı vermeyi, propaganda yapmayı ve greve veya grev teşebbüsüne katılmayı yasaklar.' },
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: 'Sicil ve başarı değerlendirmesinde 90 ve üzeri puan alan sözleşmeli personel hangi düzeyde değerlendirilir?', choices: ['A düzeyi', 'B düzeyi', 'C düzeyi', 'D düzeyi'], answer: 0, reference: '399 Sayılı KHK · Madde 42', explanation: 'Madde 42’ye göre 90 ve daha yukarı puan A düzeyi başarıyı ifade eder.' },
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: 'Disiplin cezasına karşı itiraz süresi, kararın ilgiliye tebliğinden itibaren kaç gündür?', choices: ['5 gün', '7 gün', '10 gün', '15 gün'], answer: 1, reference: '399 Sayılı KHK · Madde 47', explanation: 'Madde 47’de disiplin cezalarına karşı yedi gün içinde itiraz edilebileceği düzenlenmiştir.' },
  { topic: '399 Sayılı Kanun Hükmünde Kararname', text: 'Sicil ve başarı değerlendirmesi D düzeyinde olan personel için ilk aşamada hangi işlem uygulanır?', choices: ['Doğrudan emekliye sevk edilir', 'Altı ay başka bir sicil amiri yanında denenmek üzere yeni sözleşme yapılır', 'Ücreti artırılır', 'Sınavsız başka kuruma atanır'], answer: 1, reference: '399 Sayılı KHK · Madde 43/a', explanation: 'Madde 43/a, D düzeyinde olan personelin başka bir sicil amiri yanında altı ay daha denenmesini öngörür.' }
];
